### PR TITLE
Fix workflows (notice and changelog verifier) for 1.3.x

### PR DESCRIPTION
**Pull request by kajetan-nobel**
## Note: 

`NOTICE.txt` has to be created by using `npm run notice:generate`

### CODE REVIEW

**Review by salyh — CHANGES_REQUESTED** [review]
I dont think it is correct to change the NOTICE.txt because this is not the final NOTICE.txt shipped with the final artifact but only a template whereas everything will be appended automatically

**Comment by kajetan-nobel** [comment]
But the new one was generated with CLI which is required by workflow and as long as it is treated as "incorrect" it'll fail actions.

https://github.com/eliatra-opensearch-enterprise-distro/OpenSearch-Dashboards/actions/runs/8046341898/job/21973380824?pr=9

**Comment by salyh** [comment]
i see

**Comment by salyh** [comment]
but for 2.11 it works, right?

**Comment by kajetan-nobel** [comment]
For 2.11 I'll have to prepare a similar PR as it contains the same issues.

**Review by salyh — APPROVED** [review]

**Pull request merged**
